//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

namespace FEM.TerminalGui
{
    using Terminal.Gui;


    public partial class MyView
    {
        public MyView()
        {
            InitializeComponent();
            button1.Clicked += () => MessageBox.Query("Hello", "Launch the FEM.Core application", "Ok");
        }
    }
}