<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
        <PackageId>FEM.SharedCore</PackageId>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin\Release\FEM.Common.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <None Update="Scripts\draw_mesh_script.py">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="8.0.0" />
      <PackageReference Include="AutoMapper" Version="13.0.1" />
      <PackageReference Include="Splat.Autofac" Version="15.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FEM.SharedDTO\FEM.SharedDTO.csproj" />
      <ProjectReference Include="..\FEM.Solvers\FEM.Solvers.csproj" />
      <ProjectReference Include="..\FEM.Storage\FEM.Storage.csproj" />
    </ItemGroup>

</Project>
