<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>41cd6c9e-8222-4a89-a254-3f2b5bbe764b</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<LangVersion>13</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
	  <OutputPath>../Redist</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
		<PackageReference Include="NLog.Web.AspNetCore" Version="5.3.12" />
		<PackageReference Include="NSwag.AspNetCore" Version="14.1.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Scripts\draw_mesh_script.py">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Stationary.Core\Stationary.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <_ContentIncludedByDefault Remove="TestResults\63dccfe9-ee02-49d4-b4dd-6fa366b28780.json" />
	  <_ContentIncludedByDefault Remove="TestResults\dd3e6011-632b-4e8c-89d2-d6dfecb2b4f5.json" />
	</ItemGroup>

</Project>