<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FEM.SharedCore\FEM.SharedCore.csproj" />
      <ProjectReference Include="..\Stationary.DTO\Stationary.DTO.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Installers\" />
    </ItemGroup>

</Project>
